blank_issues_enabled: true
contact_links:
  - name: 🐞 Сообщить об ошибке
    url: https://github.com/xray-panel/subscription-page/issues/new
    about: Ошибка в этом репозитории
  - name: 💡 Предложить улучшение
    url: https://github.com/xray-panel/subscription-page/issues/new
    about: Идея или улучшение
